(function(g){var window=this;var Cza=function(a,b,c,d){var e=b.fc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.nd(c,d?d:"mqdefault.jpg");var k=b instanceof g.nQ?g.FX(b.lengthSeconds):null,l=!!f;f=l&&"RD"==g.tS(f).type;var m=b instanceof g.nQ?b.xa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.vn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.vS&&(c.playlist_length=b.getLength());a.update(c)},g7=function(a,b){g.EX.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.N=!1},h7=function(a){var b={H:"span",
M:"ytp-upnext-top",K:[{H:"span",M:"ytp-upnext-header",K:[g.U("YTP_PLAYLIST_UP_NEXT")]},{H:"span",M:"ytp-upnext-title",K:["{{title}}"]},{H:"span",M:"ytp-upnext-author",K:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={H:"div",M:"ytp-upnext",W:{"aria-label":"{{watch}}"},K:[{H:"div",M:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},b,{H:"a",M:"ytp-upnext-autoplay-icon",W:c,K:[{H:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},
K:[{H:"circle",M:"ytp-svg-autoplay-circle",W:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",M:"ytp-svg-autoplay-ring",W:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",M:"ytp-svg-autoplay-triangle",W:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",M:"ytp-upnext-bottom",K:[{H:"span",M:"ytp-upnext-cancel"},{H:"span",M:"ytp-upnext-paused",K:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]}]};
g.Y.call(this,b);this.B=null;b=this.sa["ytp-upnext-cancel"];this.B=new g.Y({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":g.U("YTP_AUTOPLAY_CANCEL")},K:[g.U("YTP_CANCEL")]});g.M(this,this.B);this.B.V("click",this.eO,this);this.B.Ba(b);this.o=a;this.J=this.sa["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.It(this.Km,5E3,this);g.M(this,this.G);this.I=0;this.P(this.sa["ytp-upnext-autoplay-icon"],"click",this.lQ);this.sA();this.P(a,"autonavvisibility",
this.sA);this.P(a,"mdxnowautoplaying",this.AP);this.P(a,"mdxautoplaycanceled",this.BP);this.P(a,"mdxautoplayupnext",this.MC);3==this.o.Qa()&&(a=(a=g.NW(g.IW(this.o)))?a.sH():null)&&this.MC(a)},Dza=function(a,b){a.C=b;
Cza(a,b,g.X(a.o),"hqdefault.jpg")},i7=function(a,b){a.A||(g.XG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.I=g.iH(),a.A=new g.It((0,g.y)(a.Kp,a,b),25),a.Kp(b));
g.$p(a.element,"ytp-upnext-autoplay-paused")},k7=function(a){j7(a);
a.I=g.iH();a.Kp();g.S(a.element,"ytp-upnext-autoplay-paused")},j7=function(a){a.A&&(a.A.dispose(),a.A=null)},l7=function(a,b){b=void 0===b?!1:b;
var c=g.X(a.o);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.WW(a.o,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.C.fc(),a.Km(),a.D=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.nd(c)}),a.F=a.P(a.D,"click",a.bQ),a.G.start())}j7(a);a.o.yj(!1,b)},Eza=function(a){g7.call(this,a,"subscribecard-endscreen");
var b=a.ga();this.A=new g.Y({H:"div",M:"ytp-subscribe-card",K:[{H:"img",M:"ytp-author-image",W:{src:b.profilePicture}},{H:"div",M:"ytp-subscribe-card-right",K:[{H:"div",M:"ytp-author-name",K:[b.author]},{H:"div",M:"html5-subscribe-button-container"}]}]});g.M(this,this.A);this.A.Ba(this.element);this.B=new g.o1(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Cl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.B);this.B.Ba(this.A.sa["html5-subscribe-button-container"]);this.hide()},
m7=function(a){var b=g.X(a),c=g.IL||g.$e?{style:"will-change: opacity"}:void 0,d=b.B&&!b.F,e=["ytp-videowall-still"];
b.experiments.g("web_player_video_wall_show_text")&&b.isMobile&&e.push("ytp-videowall-show-text");g.Y.call(this,{H:"a",ca:e,W:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{H:"div",M:"ytp-videowall-still-image",W:{style:"{{background}}"}},{H:"span",M:"ytp-videowall-still-info",K:[{H:"span",M:"ytp-videowall-still-info-bg",K:[{H:"span",M:"ytp-videowall-still-info-content",W:c,K:[{H:"span",M:"ytp-videowall-still-info-title",
K:["{{title}}"]},{H:"span",M:"ytp-videowall-still-info-author",K:["{{author_and_views}}"]},{H:"span",M:"ytp-videowall-still-info-live",K:[g.U("YTP_LIVE")]},{H:"span",M:"ytp-videowall-still-info-duration",K:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (",{H:"span",K:["{{playlist_length}}"]},")"]}]},{H:"span",
ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (50+)"]}]}]});this.B=d;this.o=a;this.A=null;this.V("click",this.C);this.V("keypress",this.D);g.X(a).ba&&(a=a.app.da,b=this.element,g.G(a.g,b),g.qb(a.g,b),c=String(a.G++),b.setAttribute("data-visual-id",c),g.Ve(this,(0,g.y)(a.F,a,b)))},n7=function(a){g7.call(this,a,"videowall-endscreen");
this.ba=a;this.G=0;this.B=[];this.I=this.D=this.C=null;this.J=this.T=!1;this.F=new g.EG(this);g.M(this,this.F);this.L=new g.It(g.Ea(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":g.U("YTP_PREVIOUS")},K:[g.CE()]});g.M(this,b);b.Ba(this.element);b.V("click",this.LK,this);this.O=new g.mX({H:"div",M:"ytp-endscreen-content"});g.M(this,this.O);this.O.Ba(this.element);b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-next"],
W:{"aria-label":g.U("YTP_NEXT")},K:[g.DE()]});g.M(this,b);b.Ba(this.element);b.V("click",this.KK,this);this.A=new h7(a);g.M(this,this.A);g.eX(this.o,this.A.element,4);this.hide()},o7=function(a){return g.fX(a.o)&&a.Op()&&!a.I},Fza=function(a){return(0,g.H)(a.suggestions,function(a){return g.r_(a)})},p7=function(a){var b=a.ls();
b!=a.T&&(a.T=b,a.o.U("autonavvisibility"))},q7=function(a){g.AX.call(this,a);
g.xE({});this.o=null;this.A=new g.EG(this);g.M(this,this.A);this.B=g.X(a);Gza(a)?this.o=new n7(this.g):this.B.ma?this.o=new Eza(this.g):this.o=new g7(this.g);g.M(this,this.o);g.eX(this.g,this.o.element,4);this.EB();this.A.P(a,"videodatachange",this.EB,this);this.A.P(a,"crn_endscreen",this.mK,this);this.A.P(a,"crx_endscreen",this.nK,this)},Gza=function(a){a=g.X(a);
return a.fd&&!a.ma};g.p(g7,g.EX);g7.prototype.create=function(){this.N=!0};
g7.prototype.destroy=function(){this.N=!1};
g7.prototype.Op=function(){return!1};
g7.prototype.ls=function(){return!1};g.p(h7,g.Y);g.h=h7.prototype;g.h.Km=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.sA=function(){g.tX(this,g.JW(this.o))};
g.h.bQ=function(){window.focus();this.Km()};
g.h.hide=function(){g.Y.prototype.hide.call(this)};
g.h.Kp=function(a){a=a||g.X(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min(g.iH()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Qa()?l7(this,!0):this.A&&this.A.start()};
g.h.lQ=function(a){!g.Pd(this.B.element,g.uG(a))&&g.e_(a,this.o)&&l7(this)};
g.h.eO=function(){g.LW(this.o,!0)};
g.h.AP=function(a){this.o.Qa();this.show();i7(this,a)};
g.h.MC=function(a){this.o.Qa();this.C&&this.C.fc().videoId==a.fc().videoId||Dza(this,a)};
g.h.BP=function(){this.o.Qa();j7(this);this.hide()};
g.h.X=function(){j7(this);this.Km();g.Y.prototype.X.call(this)};g.p(Eza,g7);g.p(m7,g.Y);m7.prototype.Nj=function(){var a=this.A.fc().videoId,b=this.A.getPlaylistId();g.Y1(this.o.app,a,this.A.Ud,b,void 0,void 0,void 0)};
m7.prototype.C=function(a){g.iX(this.o,this.element);g.e_(a,this.o,this.B,this.A.Ud||void 0)&&this.Nj()};
m7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.zG(a)||(this.Nj(),g.yG(a))}};g.p(n7,g7);g.h=n7.prototype;g.h.create=function(){g7.prototype.create.call(this);var a=this.o.ga();a&&(this.C=Fza(a),this.D=a);this.sh();this.F.P(this.o,"appresize",this.sh);this.F.P(this.o,"videodatachange",this.MK);this.F.P(this.o,"autonavchange",this.Wy);this.F.P(this.o,"autonavcancel",this.JK);this.F.P(this.element,"transitionend",this.rR)};
g.h.destroy=function(){g.GG(this.F);g.Xe(this.B);this.B=[];this.C=null;g7.prototype.destroy.call(this);g.$p(this.element,"ytp-show-tiles");this.L.stop()};
g.h.Op=function(){return 1!=this.D.autonavState};
g.h.show=function(){g7.prototype.show.call(this);g.$p(this.element,"ytp-show-tiles");g.X(this.o).isMobile?g.Kt(this.L):this.L.start();(this.J||this.I&&this.I!=this.D.clientPlaybackNonce)&&g.LW(this.o,!1);var a=o7(this);g.fX(this.o)&&g.X(this.o).experiments.g("ui_logging")&&g.WW(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.Op()?"enabled":"disabled"});a?(p7(this),2==this.D.autonavState?g.X(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.pi()?l7(this.A,!0):i7(this.A):3==this.D.autonavState&&
k7(this.A)):(g.LW(this.o,!0),p7(this))};
g.h.hide=function(){g7.prototype.hide.call(this);k7(this.A);p7(this)};
g.h.rR=function(a){g.uG(a)==this.element&&this.sh()};
g.h.sh=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.Hh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(d<f||e<k);){var q=d/2,r=e/2,v=d<=f-2&&n>=r*m,B=e<=k-2&&n>=q*m;if((q+1)/r*c/b>b/(q/(r+1)*c)&&B)n-=q*m,e+=2;else if(v)n-=r*m,d+=2;else if(B)n-=q*m,e+=2;else break}c=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=d)&&(c=!0);m=96*
d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.$c(a.width/m||1,1,1.21);n*=g.$c(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Gh(a,m,n);g.oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});Dza(this.A,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",o7(this));p7(this);m+=4;n+=4;for(f=b=0;f<d;f++)for(k=0;k<e;k++)if(q=b,r=0,c&&f>=d-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.ad(q+this.G,l),0!=
r){v=this.B[b];v||(v=new m7(this.o),this.B[b]=v,a.appendChild(v.element));B=Math.floor(n*k/e);var E=Math.floor(m*f/d),I=Math.floor(n*(k+r)/e)-B-4,R=Math.floor(m*(f+r)/d)-E-4;g.vh(v.element,E,B);g.Gh(v.element,R,I);g.oh(v.element,"transitionDelay",(k+f)/20+"s");g.T(v.element,"ytp-videowall-still-mini",1==r);g.T(v.element,"ytp-videowall-still-large",2<r);r=v;q=this.C[q];r.A=q;Cza(r,q,g.X(r.o),g.Yp(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");v=q.Ud;q=r.o;g.X(q).ba&&(q=q.app.da,
r=r.element,v=v&&v.itct,B=r.getAttribute("data-visual-id"),g.G(q.g,r),g.gX(q,"onLogServerVeCreated",{id:B,tracking_params:v}));b++}g.T(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.Hd(e.element),g.We(e);this.B.length=b}};
g.h.MK=function(){var a=this.o.ga();this.D!=a&&(this.G=0,this.C=Fza(a),this.D=a,this.sh())};
g.h.KK=function(){this.G+=this.B.length;this.sh()};
g.h.LK=function(){this.G-=this.B.length;this.sh()};
g.h.BJ=function(){return!!this.A.A};
g.h.Wy=function(a){1==a?(this.J=!1,this.I=this.D.clientPlaybackNonce,j7(this.A),this.g&&this.sh()):(this.J=!0,this.g&&o7(this)&&(2==a?i7(this.A):3==a&&k7(this.A)))};
g.h.JK=function(a){if(a){for(a=0;a<this.B.length;a++)g.jX(this.ba,this.B[a].element,!0);this.Wy(1)}else this.I=null,this.J=!1;this.sh()};
g.h.ls=function(){return this.g&&o7(this)};g.p(q7,g.AX);g.h=q7.prototype;g.h.Sy=function(){var a=this.g.ga(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Gza(this.g)||b;a=g.GQ(a,"ypc_module");var c=g.Z1(this.g.app);return b&&!a&&!c};
g.h.Ry=function(){return this.o.ls()};
g.h.yJ=function(){return this.Ry()?this.o.BJ():!1};
g.h.X=function(){g.cX(this.g,"endscreen");g.AX.prototype.X.call(this)};
g.h.load=function(){g.AX.prototype.load.call(this);this.o.show();g.X(this.g).ma&&.01>Math.random()&&g.WW(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.AX.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.mK=function(a){this.Sy()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.nK=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.EB=function(){g.cX(this.g,"endscreen");var a=Math.max(1E3*(this.g.ga().lengthSeconds-10),0);a=new g.pS(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.pS(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.$W(this.g,[a,b])};g.TZ.endscreen=q7;})(_yt_player);
