document.write('<style>');
document.write('.header_wrap {height:40px!important;overflow:hidden;z-index:100;position:relative;}');
document.write('.header_wrap {background:url(http://www.toei-anim.co.jp/common/images/bg_header_lineup.gif) left top repeat-x;}');
document.write('.header_wrap ul {list-style-type:none;margin:0;padding:0;width:810px!important;margin:0 auto;}');
document.write('.header_wrap ul li {float:left;margin:0;padding:0;line-height:1px;}');
document.write('.header_wrap ul li a img {border:none;}');
document.write('.header_wrap ul li a {display:block;height:40px!important;}');
document.write('.header_wrap ul li.logo a {width:192px!important;}');
document.write('.header_wrap ul li.home {width:63px!important;height:40px!important;}');
document.write('.header_wrap ul li.home a {background:url(http://www.toei-anim.co.jp/common/images/btn_home.gif) left top no-repeat;width:63px!important;text-indent:-9999px;}');
document.write('.header_wrap ul li.home a:hover {background:url(http://www.toei-anim.co.jp/common/images/btn_home_o.gif) left top no-repeat;}');
document.write('.header_wrap ul li.lineup {width:75px!important;height:40px!important;}');
document.write('.header_wrap ul li.lineup a {background:url(http://www.toei-anim.co.jp/common/images/btn_lineup.gif) left top no-repeat;width:75px!important;text-indent:-9999px;}');
document.write('.header_wrap ul li.lineup a:hover {background:url(http://www.toei-anim.co.jp/common/images/btn_lineup_o.gif) left top no-repeat;}');
document.write('.header_wrap ul li.movie {width:74px!important;height:40px!important;}');
document.write('.header_wrap ul li.movie a {background:url(http://www.toei-anim.co.jp/common/images/btn_movie.gif) left top no-repeat;width:74px!important;text-indent:-9999px;}');
document.write('.header_wrap ul li.movie a:hover {background:url(http://www.toei-anim.co.jp/common/images/btn_movie_o.gif) left top no-repeat;}');
document.write('.header_wrap ul li.mobile {width:75px!important;height:40px!important;}');
document.write('.header_wrap ul li.mobile a {background:url(http://www.toei-anim.co.jp/common/images/btn_60th.gif) left top no-repeat;width:75px!important;text-indent:-9999px;}');
document.write('.header_wrap ul li.mobile a:hover {background:url(http://www.toei-anim.co.jp/common/images/btn_60th_o.gif) left top no-repeat;}');
document.write('.header_wrap ul li.game {width:66px!important;height:40px!important;}');
document.write('.header_wrap ul li.game a {background:url(http://www.toei-anim.co.jp/common/images/btn_game.gif) left top no-repeat;width:66px!important;text-indent:-9999px;}');
document.write('.header_wrap ul li.game a:hover {background:url(http://www.toei-anim.co.jp/common/images/btn_game_o.gif) left top no-repeat;}');
document.write('.header_wrap ul li.event {width:74px!important;height:40px!important;}');
document.write('.header_wrap ul li.event a {background:url(http://www.toei-anim.co.jp/common/images/btn_event.gif) left top no-repeat;width:74px!important;text-indent:-9999px;}');
document.write('.header_wrap ul li.event a:hover {background:url(http://www.toei-anim.co.jp/common/images/btn_event_o.gif) left top no-repeat;}');
document.write('.header_wrap ul li.shopping {width:95px!important;height:40px!important;}');
document.write('.header_wrap ul li.shopping a {background:url(http://www.toei-anim.co.jp/common/images/btn_shopping.gif) left top no-repeat;width:95px!important;text-indent:-9999px;}');
document.write('.header_wrap ul li.shopping a:hover {background:url(http://www.toei-anim.co.jp/common/images/btn_shopping_o.gif) left top no-repeat;}');
document.write('.header_wrap ul li.club {width:87px!important;height:40px!important;}');
document.write('.header_wrap ul li.club a {background:url(http://www.toei-anim.co.jp/common/images/btn_club.gif) left top no-repeat;width:87px!important;text-indent:-9999px;}');
document.write('.header_wrap ul li.club a:hover {background:url(http://www.toei-anim.co.jp/common/images/btn_club_o.gif) left top no-repeat;}');
document.write('</style>');
document.write('<div class="header_wrap">');
document.write('	<ul>');
document.write('		<li class="logo"><a href="http://www.toei-anim.co.jp/"><img src="http://www.toei-anim.co.jp/common/images/logo_torei.gif" /></a></li>');
document.write('		<li class="home"><a href="http://www.toei-anim.co.jp/">&nbsp;</a></li>');
document.write('		<li class="lineup"><a href="http://www.toei-anim.co.jp/lineup/">&nbsp;</a></li>');
document.write('		<li class="movie"><a href="http://taod.jp/" target="_blank">&nbsp;</a></li>');
document.write('		<li class="mobile"><a href="http://60th.toei-anim.co.jp/">&nbsp;</a></li>');
document.write('		<li class="game"><a href="http://www.toei-anim.co.jp/game/">&nbsp;</a></li>');
document.write('		<li class="event"><a href="http://www.toei-anim.co.jp/news/">&nbsp;</a></li>');
document.write('		<li class="shopping"><a href="http://shopping.toei-anim.co.jp/">&nbsp;</a></li>');
document.write('		<li class="club"><a href="http://www.toei-anim.co.jp/entry/kiyaku.php">&nbsp;</a></li>');
document.write('	</ul>');
document.write('</div>');